# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Code\Python\PyQt\vocabulary_learning\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 363)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.choose_dict_label = QtWidgets.QLabel(self.centralwidget)
        self.choose_dict_label.setObjectName("choose_dict_label")
        self.horizontalLayout.addWidget(self.choose_dict_label)
        self.choose_dict = QtWidgets.QComboBox(self.centralwidget)
        self.choose_dict.setObjectName("choose_dict")
        self.horizontalLayout.addWidget(self.choose_dict)
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setObjectName("start_button")
        self.horizontalLayout.addWidget(self.start_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.word_input = QtWidgets.QLineEdit(self.centralwidget)
        self.word_input.setObjectName("word_input")
        self.horizontalLayout_2.addWidget(self.word_input)
        self.search_button = QtWidgets.QPushButton(self.centralwidget)
        self.search_button.setObjectName("search_button")
        self.horizontalLayout_2.addWidget(self.search_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "弹窗背单词"))
        self.choose_dict_label.setText(_translate("MainWindow", "选择词库"))
        self.start_button.setText(_translate("MainWindow", "开始"))
        self.label.setText(_translate("MainWindow", "查单词"))
        self.search_button.setText(_translate("MainWindow", "查询"))
        self.search_button.setShortcut(_translate("MainWindow", "Return"))
